import { Effect } from "effect";

import { EmptyFragmentContentError, NodePathCollisionError } from "./errors";
import type { BoeFragment } from "./types";

export const assertFragmentInvariants = (
  fragments: ReadonlyArray<BoeFragment>,
): Effect.Effect<void, NodePathCollisionError | EmptyFragmentContentError> =>
  Effect.gen(function* () {
    const seenPaths = new Set<string>();

    for (const [index, fragment] of fragments.entries()) {
      if (seenPaths.has(fragment.nodePath)) {
        return yield* new NodePathCollisionError({
          nodePath: fragment.nodePath,
          message: `Duplicate node path '${fragment.nodePath}' generated by BOE parser`,
        });
      }

      seenPaths.add(fragment.nodePath);

      if (fragment.contentNormalized.length === 0) {
        return yield* new EmptyFragmentContentError({
          nodePath: fragment.nodePath,
          message: `Empty fragment content for path '${fragment.nodePath}'`,
        });
      }

      if (fragment.sequenceIndex !== index) {
        return yield* new NodePathCollisionError({
          nodePath: fragment.nodePath,
          message: `Unexpected sequence index '${fragment.sequenceIndex}' for '${fragment.nodePath}'`,
        });
      }
    }
  });
