[package]
name = "parser-benchcmp-harness"
version = "0.1.0"
edition = "2024"
autobenches = false
publish = false

[workspace]

[workspace.dependencies]
criterion          = { version = "0.8.2", features = ["html_reports"] }
gungraun           = "0.19.0"

document-hierarchy = { path = "../../../crates/parser" }

[lib]
bench = false

[dependencies]
document-hierarchy.workspace = true

[dev-dependencies]
criterion.workspace = true
gungraun.workspace  = true

[[bench]]
name = "criterion_compare"
harness = false

[[bench]]
name = "gungraun_compare"
harness = false
