[tools]
bun                   = "1.4.2"
"cargo:cargo-insta"   = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:surrealkit"    = "0.7.0"
just                  = "latest"
node                  = "26"
taplo                 = { version = "latest", matching = "full" }

[env]
DO_NOT_TRACK = "1"

[hooks]
enter = "bunx --no-install varlock load --agent > /dev/null"
