/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthThreadsRouteRouteImport } from './routes/_auth/threads/route'
import { Route as AuthThreadsIndexRouteImport } from './routes/_auth/threads/index'
import { Route as ApiSyncShapeRouteImport } from './routes/api/sync/$shape'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthThreadsThreadIdRouteImport } from './routes/_auth/threads/$threadId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthThreadsRouteRoute = AuthThreadsRouteRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => AuthRoute,
} as any)
const AuthThreadsIndexRoute = AuthThreadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthThreadsRouteRoute,
} as any)
const ApiSyncShapeRoute = ApiSyncShapeRouteImport.update({
  id: '/api/sync/$shape',
  path: '/api/sync/$shape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthThreadsThreadIdRoute = AuthThreadsThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AuthThreadsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/threads': typeof AuthThreadsRouteRouteWithChildren
  '/threads/$threadId': typeof AuthThreadsThreadIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/sync/$shape': typeof ApiSyncShapeRoute
  '/threads/': typeof AuthThreadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/threads/$threadId': typeof AuthThreadsThreadIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/sync/$shape': typeof ApiSyncShapeRoute
  '/threads': typeof AuthThreadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/_auth/threads': typeof AuthThreadsRouteRouteWithChildren
  '/_auth/threads/$threadId': typeof AuthThreadsThreadIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/sync/$shape': typeof ApiSyncShapeRoute
  '/_auth/threads/': typeof AuthThreadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent'
    | '/login'
    | '/threads'
    | '/threads/$threadId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/sync/$shape'
    | '/threads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/login'
    | '/threads/$threadId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/sync/$shape'
    | '/threads'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/consent'
    | '/login'
    | '/_auth/threads'
    | '/_auth/threads/$threadId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/sync/$shape'
    | '/_auth/threads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiSyncShapeRoute: typeof ApiSyncShapeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/threads': {
      id: '/_auth/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof AuthThreadsRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/threads/': {
      id: '/_auth/threads/'
      path: '/'
      fullPath: '/threads/'
      preLoaderRoute: typeof AuthThreadsIndexRouteImport
      parentRoute: typeof AuthThreadsRouteRoute
    }
    '/api/sync/$shape': {
      id: '/api/sync/$shape'
      path: '/api/sync/$shape'
      fullPath: '/api/sync/$shape'
      preLoaderRoute: typeof ApiSyncShapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/threads/$threadId': {
      id: '/_auth/threads/$threadId'
      path: '/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof AuthThreadsThreadIdRouteImport
      parentRoute: typeof AuthThreadsRouteRoute
    }
  }
}

interface AuthThreadsRouteRouteChildren {
  AuthThreadsThreadIdRoute: typeof AuthThreadsThreadIdRoute
  AuthThreadsIndexRoute: typeof AuthThreadsIndexRoute
}

const AuthThreadsRouteRouteChildren: AuthThreadsRouteRouteChildren = {
  AuthThreadsThreadIdRoute: AuthThreadsThreadIdRoute,
  AuthThreadsIndexRoute: AuthThreadsIndexRoute,
}

const AuthThreadsRouteRouteWithChildren =
  AuthThreadsRouteRoute._addFileChildren(AuthThreadsRouteRouteChildren)

interface AuthRouteChildren {
  AuthThreadsRouteRoute: typeof AuthThreadsRouteRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthThreadsRouteRoute: AuthThreadsRouteRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ConsentRoute: ConsentRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiSyncShapeRoute: ApiSyncShapeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
