// Generated by scripts/replica.ts. Run `bun run db:generate` after Drizzle or replica changes.
export const cache = {
  "threads": 1246756938855211,
  "messages": 1133860948347755,
  "runs": 2836944689802478,
  "events": 2475700200688494,
  "parts": 1536371969969558
} as const;

export const manifest = {
  "format": 2,
  "database": {
    "dialect": "postgres",
    "head": {
      "migration": "20260926103204_breezy_shiva",
      "prevIds": [
        "a9e5cb48-5981-4228-be99-91fd94993d5e"
      ],
      "snapshotDigest": "sha256:66b2fec48ab4b5d616019ee105f6d2a3a4eb25ba5bf07d8a797b5ad566a97b72",
      "snapshotId": "76560928-2f92-4850-a42b-cfeee215a4b1",
      "sqlDigest": "sha256:e265b32180cf7fc7522d7a1e72602eb5d3fcb25d11a8c3cff35f0bb32bdfeae3",
      "timestamp": 1790418724000
    },
    "history": [
      {
        "migration": "20260621034535_noisy_sunspot",
        "prevIds": [
          "00000000-0000-0000-0000-000000000000"
        ],
        "snapshotDigest": "sha256:43c5bef071506af0ae0d19ab944c7f86d7c338f824ede905c44f36435e59bfb1",
        "snapshotId": "20c061d3-c910-49d0-966f-6eb9709dc576",
        "sqlDigest": "sha256:d855e90ef5f1c144ed0cc390aaca484648a24d2e74dceea11f59493d4a7840fc",
        "timestamp": 1782013535000
      },
      {
        "migration": "20260621212926_graceful_ezekiel_stane",
        "prevIds": [
          "20c061d3-c910-49d0-966f-6eb9709dc576"
        ],
        "snapshotDigest": "sha256:de860323a33a0a86b5a7b5a67a6499e7fbff2598f2810b896d159ed2571d4a20",
        "snapshotId": "7b69d89b-32b8-4d23-b70f-54b888f07aa4",
        "sqlDigest": "sha256:feebdfa79354c848be7bbb9b7db60837328e74a3fbf593219c23835a37917a51",
        "timestamp": 1782077366000
      },
      {
        "migration": "20260918100328_better_auth_1_7",
        "prevIds": [
          "7b69d89b-32b8-4d23-b70f-54b888f07aa4"
        ],
        "snapshotDigest": "sha256:65bc5d54392408dd37bef947c203b1327caad38fabb47bee009120a3e320a473",
        "snapshotId": "7a95619d-fc68-4cb9-937f-959bcddea0f0",
        "sqlDigest": "sha256:d70cc1f74f153aa27f565b5a37680e75f137faa7b252856d8c59701a0274913e",
        "timestamp": 1789725808000
      },
      {
        "migration": "20260924161106_useful_lizard",
        "prevIds": [
          "7a95619d-fc68-4cb9-937f-959bcddea0f0"
        ],
        "snapshotDigest": "sha256:382ef68bd28b20960dea79d1e8ce7d078e91fb10d618fa84cbda917f6f4016b3",
        "snapshotId": "a9e5cb48-5981-4228-be99-91fd94993d5e",
        "sqlDigest": "sha256:3117b6ac8cf06ed6f05b796add460f8e3245b5b01501f0b8ca8ce62d339c2e6f",
        "timestamp": 1790266266000
      },
      {
        "migration": "20260926103204_breezy_shiva",
        "prevIds": [
          "a9e5cb48-5981-4228-be99-91fd94993d5e"
        ],
        "snapshotDigest": "sha256:66b2fec48ab4b5d616019ee105f6d2a3a4eb25ba5bf07d8a797b5ad566a97b72",
        "snapshotId": "76560928-2f92-4850-a42b-cfeee215a4b1",
        "sqlDigest": "sha256:e265b32180cf7fc7522d7a1e72602eb5d3fcb25d11a8c3cff35f0bb32bdfeae3",
        "timestamp": 1790418724000
      }
    ],
    "historyDigest": "sha256:ce4201beb055f7034b6358e8f457fc2e48247d99b6bbc7767ab9748bd400a514"
  },
  "replicas": {
    "threads": {
      "algorithm": "sha256-canonical-json-v2",
      "cacheVersion": 1246756938855211,
      "contract": {
        "columns": [
          {
            "dimensions": 0,
            "name": "created_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "model",
            "notNull": false,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "owner_id",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "settled_at",
            "notNull": false,
            "type": "timestamp with time zone",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "snoozed_until",
            "notNull": false,
            "type": "timestamp with time zone",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "title",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "updated_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          }
        ],
        "key": "id",
        "mapper": "electric-snake-camel-v1",
        "name": "threads",
        "persistence": "tanstack-sqlite-json-v1",
        "rowSchema": {
          "$schema": "https://json-schema.org/draft/2020-12/schema",
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "ownerId": {
              "type": "string"
            },
            "title": {
              "type": "string"
            },
            "createdAt": {},
            "updatedAt": {},
            "settledAt": {
              "anyOf": [
                {},
                {
                  "type": "null"
                }
              ]
            },
            "snoozedUntil": {
              "anyOf": [
                {},
                {
                  "type": "null"
                }
              ]
            },
            "model": {
              "type": [
                "string",
                "null"
              ]
            }
          },
          "required": [
            "id",
            "ownerId",
            "title",
            "createdAt",
            "updatedAt",
            "settledAt",
            "snoozedUntil",
            "model"
          ],
          "additionalProperties": false
        },
        "schema": "public",
        "table": "thread",
        "transformer": "drizzle-zod-date-v1",
        "where": "owner_id = $1"
      },
      "digest": "sha256:46deb3876332bcc9c8acea03f21e1d6c3fc6f7e083d16018216a139123df19d0",
      "sourceDigest": "sha256:d1750f19fbb57308efacfeebfcb4bec997ba4063a664f7f733333e2f8eb28fa4"
    },
    "messages": {
      "algorithm": "sha256-canonical-json-v2",
      "cacheVersion": 1133860948347755,
      "contract": {
        "columns": [
          {
            "dimensions": 0,
            "name": "content",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "created_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "metadata",
            "notNull": false,
            "type": "jsonb",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "model",
            "notNull": false,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "owner_id",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "role",
            "notNull": true,
            "type": "message_role",
            "typeSchema": "public"
          },
          {
            "dimensions": 0,
            "name": "run_id",
            "notNull": false,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "thread_id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "updated_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          }
        ],
        "key": "id",
        "mapper": "electric-snake-camel-v1",
        "name": "messages",
        "persistence": "tanstack-sqlite-json-v1",
        "rowSchema": {
          "$schema": "https://json-schema.org/draft/2020-12/schema",
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "threadId": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "ownerId": {
              "type": "string"
            },
            "runId": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "uuid",
                  "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
                },
                {
                  "type": "null"
                }
              ]
            },
            "role": {
              "type": "string",
              "enum": [
                "user",
                "assistant",
                "system",
                "tool"
              ]
            },
            "content": {
              "type": "string"
            },
            "model": {
              "type": [
                "string",
                "null"
              ]
            },
            "metadata": {
              "anyOf": [
                {
                  "type": "object",
                  "propertyNames": {
                    "type": "string"
                  },
                  "additionalProperties": {}
                },
                {
                  "type": "null"
                }
              ]
            },
            "createdAt": {},
            "updatedAt": {}
          },
          "required": [
            "id",
            "threadId",
            "ownerId",
            "runId",
            "role",
            "content",
            "model",
            "metadata",
            "createdAt",
            "updatedAt"
          ],
          "additionalProperties": false
        },
        "schema": "public",
        "table": "message",
        "transformer": "drizzle-zod-date-v1",
        "where": "owner_id = $1"
      },
      "digest": "sha256:4073d930d0b6b0f770ad06ec41244be8dc0145c13495bb1f19a659c5eda028ce",
      "sourceDigest": "sha256:81e38c81489c25d8525eb91552b4490ca5d888c76a2a43f90ca0bea834d759ee"
    },
    "runs": {
      "algorithm": "sha256-canonical-json-v2",
      "cacheVersion": 2836944689802478,
      "contract": {
        "columns": [
          {
            "dimensions": 0,
            "name": "completed_at",
            "notNull": false,
            "type": "timestamp with time zone",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "created_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "error",
            "notNull": false,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "input_message_id",
            "notNull": false,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "model",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "owner_id",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "started_at",
            "notNull": false,
            "type": "timestamp with time zone",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "status",
            "notNull": true,
            "type": "run_status",
            "typeSchema": "public"
          },
          {
            "dimensions": 0,
            "name": "thread_id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "updated_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          }
        ],
        "key": "id",
        "mapper": "electric-snake-camel-v1",
        "name": "runs",
        "persistence": "tanstack-sqlite-json-v1",
        "rowSchema": {
          "$schema": "https://json-schema.org/draft/2020-12/schema",
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "threadId": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "ownerId": {
              "type": "string"
            },
            "inputMessageId": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "uuid",
                  "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
                },
                {
                  "type": "null"
                }
              ]
            },
            "status": {
              "type": "string",
              "enum": [
                "queued",
                "running",
                "completed",
                "cancelled",
                "failed"
              ]
            },
            "model": {
              "type": "string"
            },
            "error": {
              "type": [
                "string",
                "null"
              ]
            },
            "startedAt": {
              "anyOf": [
                {},
                {
                  "type": "null"
                }
              ]
            },
            "completedAt": {
              "anyOf": [
                {},
                {
                  "type": "null"
                }
              ]
            },
            "createdAt": {},
            "updatedAt": {}
          },
          "required": [
            "id",
            "threadId",
            "ownerId",
            "inputMessageId",
            "status",
            "model",
            "error",
            "startedAt",
            "completedAt",
            "createdAt",
            "updatedAt"
          ],
          "additionalProperties": false
        },
        "schema": "public",
        "table": "run",
        "transformer": "drizzle-zod-date-v1",
        "where": "owner_id = $1"
      },
      "digest": "sha256:a142fa87bacee690fed645c8e16a2b5479c52b631c5df6c14aa28a01ed49eaa4",
      "sourceDigest": "sha256:587d6cc9073159a1c7813f655e407822ad454074ce22e315c97fb230a8aa6e2f"
    },
    "events": {
      "algorithm": "sha256-canonical-json-v2",
      "cacheVersion": 2475700200688494,
      "contract": {
        "columns": [
          {
            "dimensions": 0,
            "name": "created_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "data",
            "notNull": false,
            "type": "jsonb",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "owner_id",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "run_id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "seq",
            "notNull": true,
            "type": "integer",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "thread_id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "type",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          }
        ],
        "key": "id",
        "mapper": "electric-snake-camel-v1",
        "name": "events",
        "persistence": "tanstack-sqlite-json-v1",
        "rowSchema": {
          "$schema": "https://json-schema.org/draft/2020-12/schema",
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "runId": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "threadId": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "ownerId": {
              "type": "string"
            },
            "seq": {
              "type": "integer",
              "minimum": -2147483648,
              "maximum": 2147483647
            },
            "type": {
              "type": "string"
            },
            "data": {
              "anyOf": [
                {
                  "type": "object",
                  "propertyNames": {
                    "type": "string"
                  },
                  "additionalProperties": {}
                },
                {
                  "type": "null"
                }
              ]
            },
            "createdAt": {}
          },
          "required": [
            "id",
            "runId",
            "threadId",
            "ownerId",
            "seq",
            "type",
            "data",
            "createdAt"
          ],
          "additionalProperties": false
        },
        "schema": "public",
        "table": "run_event",
        "transformer": "drizzle-zod-date-v1",
        "where": "owner_id = $1"
      },
      "digest": "sha256:8cba2df084b6e37a4fb9218615496d9346bffe9542ad79b381a5be15d6d7361b",
      "sourceDigest": "sha256:92680549afa5269096cbb9b0f8ac3a4694d323d70afdefb3d326d21aa5c336c2"
    },
    "parts": {
      "algorithm": "sha256-canonical-json-v2",
      "cacheVersion": 1536371969969558,
      "contract": {
        "columns": [
          {
            "dimensions": 0,
            "name": "content",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "created_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "data",
            "notNull": false,
            "type": "jsonb",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "kind",
            "notNull": true,
            "type": "message_part_kind",
            "typeSchema": "public"
          },
          {
            "dimensions": 0,
            "name": "message_id",
            "notNull": false,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "owner_id",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "run_id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "seq",
            "notNull": true,
            "type": "integer",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "status",
            "notNull": true,
            "type": "message_part_status",
            "typeSchema": "public"
          },
          {
            "dimensions": 0,
            "name": "thread_id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "tool_name",
            "notNull": false,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "updated_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          }
        ],
        "key": "id",
        "mapper": "electric-snake-camel-v1",
        "name": "parts",
        "persistence": "tanstack-sqlite-json-v1",
        "rowSchema": {
          "$schema": "https://json-schema.org/draft/2020-12/schema",
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "messageId": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "uuid",
                  "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
                },
                {
                  "type": "null"
                }
              ]
            },
            "runId": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "threadId": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "ownerId": {
              "type": "string"
            },
            "seq": {
              "type": "integer",
              "minimum": -2147483648,
              "maximum": 2147483647
            },
            "kind": {
              "type": "string",
              "enum": [
                "text",
                "reasoning",
                "tool-call",
                "tool-result",
                "artifact",
                "error",
                "status"
              ]
            },
            "status": {
              "type": "string",
              "enum": [
                "pending",
                "running",
                "completed",
                "failed",
                "cancelled"
              ]
            },
            "toolName": {
              "type": [
                "string",
                "null"
              ]
            },
            "content": {
              "type": "string"
            },
            "data": {
              "anyOf": [
                {
                  "type": "object",
                  "propertyNames": {
                    "type": "string"
                  },
                  "additionalProperties": {}
                },
                {
                  "type": "null"
                }
              ]
            },
            "createdAt": {},
            "updatedAt": {}
          },
          "required": [
            "id",
            "messageId",
            "runId",
            "threadId",
            "ownerId",
            "seq",
            "kind",
            "status",
            "toolName",
            "content",
            "data",
            "createdAt",
            "updatedAt"
          ],
          "additionalProperties": false
        },
        "schema": "public",
        "table": "message_part",
        "transformer": "drizzle-zod-date-v1",
        "where": "owner_id = $1"
      },
      "digest": "sha256:5755279834d96978f10b2916578c317bd2e20fe9b984d1de31a2bdfed6c0d036",
      "sourceDigest": "sha256:567940605a669d7d71e16a36bfff26098190598966387f9b2a8a1a4581506c4a"
    }
  }
} as const;
