// Generated by scripts/replica.ts. Run `bun run db:generate` after Drizzle or replica changes.
export const cache = {
  "threads": 1363086815048138,
  "messages": 163252237470584,
  "runs": 2836944689802478,
  "events": 2475700200688494,
  "parts": 1536371969969558
} as const;

export const manifest = {
  "format": 2,
  "database": {
    "dialect": "postgres",
    "head": {
      "migration": "20260918100328_better_auth_1_7",
      "prevIds": [
        "7b69d89b-32b8-4d23-b70f-54b888f07aa4"
      ],
      "snapshotDigest": "sha256:65bc5d54392408dd37bef947c203b1327caad38fabb47bee009120a3e320a473",
      "snapshotId": "7a95619d-fc68-4cb9-937f-959bcddea0f0",
      "sqlDigest": "sha256:d70cc1f74f153aa27f565b5a37680e75f137faa7b252856d8c59701a0274913e",
      "timestamp": 1789725808000
    },
    "history": [
      {
        "migration": "20260621034535_noisy_sunspot",
        "prevIds": [
          "00000000-0000-0000-0000-000000000000"
        ],
        "snapshotDigest": "sha256:43c5bef071506af0ae0d19ab944c7f86d7c338f824ede905c44f36435e59bfb1",
        "snapshotId": "20c061d3-c910-49d0-966f-6eb9709dc576",
        "sqlDigest": "sha256:d855e90ef5f1c144ed0cc390aaca484648a24d2e74dceea11f59493d4a7840fc",
        "timestamp": 1782013535000
      },
      {
        "migration": "20260621212926_graceful_ezekiel_stane",
        "prevIds": [
          "20c061d3-c910-49d0-966f-6eb9709dc576"
        ],
        "snapshotDigest": "sha256:de860323a33a0a86b5a7b5a67a6499e7fbff2598f2810b896d159ed2571d4a20",
        "snapshotId": "7b69d89b-32b8-4d23-b70f-54b888f07aa4",
        "sqlDigest": "sha256:feebdfa79354c848be7bbb9b7db60837328e74a3fbf593219c23835a37917a51",
        "timestamp": 1782077366000
      },
      {
        "migration": "20260918100328_better_auth_1_7",
        "prevIds": [
          "7b69d89b-32b8-4d23-b70f-54b888f07aa4"
        ],
        "snapshotDigest": "sha256:65bc5d54392408dd37bef947c203b1327caad38fabb47bee009120a3e320a473",
        "snapshotId": "7a95619d-fc68-4cb9-937f-959bcddea0f0",
        "sqlDigest": "sha256:d70cc1f74f153aa27f565b5a37680e75f137faa7b252856d8c59701a0274913e",
        "timestamp": 1789725808000
      }
    ],
    "historyDigest": "sha256:23245763a9e8c7a2d39f1a85615d2475e390930f0859f455242aca8a6ba24b14"
  },
  "replicas": {
    "threads": {
      "algorithm": "sha256-canonical-json-v2",
      "cacheVersion": 1363086815048138,
      "contract": {
        "columns": [
          {
            "dimensions": 0,
            "name": "archived_at",
            "notNull": false,
            "type": "timestamp with time zone",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "created_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "owner_id",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "title",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "updated_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          }
        ],
        "key": "id",
        "mapper": "electric-snake-camel-v1",
        "name": "threads",
        "persistence": "tanstack-sqlite-json-v1",
        "rowSchema": {
          "$schema": "https://json-schema.org/draft/2020-12/schema",
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "ownerId": {
              "type": "string"
            },
            "title": {
              "type": "string"
            },
            "createdAt": {},
            "updatedAt": {},
            "archivedAt": {
              "anyOf": [
                {},
                {
                  "type": "null"
                }
              ]
            }
          },
          "required": [
            "id",
            "ownerId",
            "title",
            "createdAt",
            "updatedAt",
            "archivedAt"
          ],
          "additionalProperties": false
        },
        "schema": "public",
        "table": "thread",
        "transformer": "drizzle-zod-date-v1",
        "where": "owner_id = $1 and archived_at is null"
      },
      "digest": "sha256:4d7b86168b1ca2f8b3b84bf6ac4dc2c176d959f0fdb1f348963640a5761e06f0",
      "sourceDigest": "sha256:28e158d42ed6e5923fd9ef06ba3fefeb57545c27781e685dd3b053aee6302d6d"
    },
    "messages": {
      "algorithm": "sha256-canonical-json-v2",
      "cacheVersion": 163252237470584,
      "contract": {
        "columns": [
          {
            "dimensions": 0,
            "name": "content",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "created_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "metadata",
            "notNull": false,
            "type": "jsonb",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "owner_id",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "role",
            "notNull": true,
            "type": "message_role",
            "typeSchema": "public"
          },
          {
            "dimensions": 0,
            "name": "run_id",
            "notNull": false,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "thread_id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "updated_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          }
        ],
        "key": "id",
        "mapper": "electric-snake-camel-v1",
        "name": "messages",
        "persistence": "tanstack-sqlite-json-v1",
        "rowSchema": {
          "$schema": "https://json-schema.org/draft/2020-12/schema",
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "threadId": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "ownerId": {
              "type": "string"
            },
            "runId": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "uuid",
                  "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
                },
                {
                  "type": "null"
                }
              ]
            },
            "role": {
              "type": "string",
              "enum": [
                "user",
                "assistant",
                "system",
                "tool"
              ]
            },
            "content": {
              "type": "string"
            },
            "metadata": {
              "anyOf": [
                {
                  "type": "object",
                  "propertyNames": {
                    "type": "string"
                  },
                  "additionalProperties": {}
                },
                {
                  "type": "null"
                }
              ]
            },
            "createdAt": {},
            "updatedAt": {}
          },
          "required": [
            "id",
            "threadId",
            "ownerId",
            "runId",
            "role",
            "content",
            "metadata",
            "createdAt",
            "updatedAt"
          ],
          "additionalProperties": false
        },
        "schema": "public",
        "table": "message",
        "transformer": "drizzle-zod-date-v1",
        "where": "owner_id = $1"
      },
      "digest": "sha256:0947a1f9f8b78251f1ad05ef45aa58b51459237e1c1bc53f81f755a962f7d0cc",
      "sourceDigest": "sha256:8f1c182751932bb26f147221db6aa8c0c0390cb3603bcd229ab75fe8d68a25b4"
    },
    "runs": {
      "algorithm": "sha256-canonical-json-v2",
      "cacheVersion": 2836944689802478,
      "contract": {
        "columns": [
          {
            "dimensions": 0,
            "name": "completed_at",
            "notNull": false,
            "type": "timestamp with time zone",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "created_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "error",
            "notNull": false,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "input_message_id",
            "notNull": false,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "model",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "owner_id",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "started_at",
            "notNull": false,
            "type": "timestamp with time zone",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "status",
            "notNull": true,
            "type": "run_status",
            "typeSchema": "public"
          },
          {
            "dimensions": 0,
            "name": "thread_id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "updated_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          }
        ],
        "key": "id",
        "mapper": "electric-snake-camel-v1",
        "name": "runs",
        "persistence": "tanstack-sqlite-json-v1",
        "rowSchema": {
          "$schema": "https://json-schema.org/draft/2020-12/schema",
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "threadId": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "ownerId": {
              "type": "string"
            },
            "inputMessageId": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "uuid",
                  "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
                },
                {
                  "type": "null"
                }
              ]
            },
            "status": {
              "type": "string",
              "enum": [
                "queued",
                "running",
                "completed",
                "cancelled",
                "failed"
              ]
            },
            "model": {
              "type": "string"
            },
            "error": {
              "type": [
                "string",
                "null"
              ]
            },
            "startedAt": {
              "anyOf": [
                {},
                {
                  "type": "null"
                }
              ]
            },
            "completedAt": {
              "anyOf": [
                {},
                {
                  "type": "null"
                }
              ]
            },
            "createdAt": {},
            "updatedAt": {}
          },
          "required": [
            "id",
            "threadId",
            "ownerId",
            "inputMessageId",
            "status",
            "model",
            "error",
            "startedAt",
            "completedAt",
            "createdAt",
            "updatedAt"
          ],
          "additionalProperties": false
        },
        "schema": "public",
        "table": "run",
        "transformer": "drizzle-zod-date-v1",
        "where": "owner_id = $1"
      },
      "digest": "sha256:a142fa87bacee690fed645c8e16a2b5479c52b631c5df6c14aa28a01ed49eaa4",
      "sourceDigest": "sha256:587d6cc9073159a1c7813f655e407822ad454074ce22e315c97fb230a8aa6e2f"
    },
    "events": {
      "algorithm": "sha256-canonical-json-v2",
      "cacheVersion": 2475700200688494,
      "contract": {
        "columns": [
          {
            "dimensions": 0,
            "name": "created_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "data",
            "notNull": false,
            "type": "jsonb",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "owner_id",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "run_id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "seq",
            "notNull": true,
            "type": "integer",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "thread_id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "type",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          }
        ],
        "key": "id",
        "mapper": "electric-snake-camel-v1",
        "name": "events",
        "persistence": "tanstack-sqlite-json-v1",
        "rowSchema": {
          "$schema": "https://json-schema.org/draft/2020-12/schema",
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "runId": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "threadId": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "ownerId": {
              "type": "string"
            },
            "seq": {
              "type": "integer",
              "minimum": -2147483648,
              "maximum": 2147483647
            },
            "type": {
              "type": "string"
            },
            "data": {
              "anyOf": [
                {
                  "type": "object",
                  "propertyNames": {
                    "type": "string"
                  },
                  "additionalProperties": {}
                },
                {
                  "type": "null"
                }
              ]
            },
            "createdAt": {}
          },
          "required": [
            "id",
            "runId",
            "threadId",
            "ownerId",
            "seq",
            "type",
            "data",
            "createdAt"
          ],
          "additionalProperties": false
        },
        "schema": "public",
        "table": "run_event",
        "transformer": "drizzle-zod-date-v1",
        "where": "owner_id = $1"
      },
      "digest": "sha256:8cba2df084b6e37a4fb9218615496d9346bffe9542ad79b381a5be15d6d7361b",
      "sourceDigest": "sha256:92680549afa5269096cbb9b0f8ac3a4694d323d70afdefb3d326d21aa5c336c2"
    },
    "parts": {
      "algorithm": "sha256-canonical-json-v2",
      "cacheVersion": 1536371969969558,
      "contract": {
        "columns": [
          {
            "dimensions": 0,
            "name": "content",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "created_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "data",
            "notNull": false,
            "type": "jsonb",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "kind",
            "notNull": true,
            "type": "message_part_kind",
            "typeSchema": "public"
          },
          {
            "dimensions": 0,
            "name": "message_id",
            "notNull": false,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "owner_id",
            "notNull": true,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "run_id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "seq",
            "notNull": true,
            "type": "integer",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "status",
            "notNull": true,
            "type": "message_part_status",
            "typeSchema": "public"
          },
          {
            "dimensions": 0,
            "name": "thread_id",
            "notNull": true,
            "type": "uuid",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "tool_name",
            "notNull": false,
            "type": "text",
            "typeSchema": null
          },
          {
            "dimensions": 0,
            "name": "updated_at",
            "notNull": true,
            "type": "timestamp with time zone",
            "typeSchema": null
          }
        ],
        "key": "id",
        "mapper": "electric-snake-camel-v1",
        "name": "parts",
        "persistence": "tanstack-sqlite-json-v1",
        "rowSchema": {
          "$schema": "https://json-schema.org/draft/2020-12/schema",
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "messageId": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "uuid",
                  "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
                },
                {
                  "type": "null"
                }
              ]
            },
            "runId": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "threadId": {
              "type": "string",
              "format": "uuid",
              "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
            },
            "ownerId": {
              "type": "string"
            },
            "seq": {
              "type": "integer",
              "minimum": -2147483648,
              "maximum": 2147483647
            },
            "kind": {
              "type": "string",
              "enum": [
                "text",
                "reasoning",
                "tool-call",
                "tool-result",
                "artifact",
                "error",
                "status"
              ]
            },
            "status": {
              "type": "string",
              "enum": [
                "pending",
                "running",
                "completed",
                "failed",
                "cancelled"
              ]
            },
            "toolName": {
              "type": [
                "string",
                "null"
              ]
            },
            "content": {
              "type": "string"
            },
            "data": {
              "anyOf": [
                {
                  "type": "object",
                  "propertyNames": {
                    "type": "string"
                  },
                  "additionalProperties": {}
                },
                {
                  "type": "null"
                }
              ]
            },
            "createdAt": {},
            "updatedAt": {}
          },
          "required": [
            "id",
            "messageId",
            "runId",
            "threadId",
            "ownerId",
            "seq",
            "kind",
            "status",
            "toolName",
            "content",
            "data",
            "createdAt",
            "updatedAt"
          ],
          "additionalProperties": false
        },
        "schema": "public",
        "table": "message_part",
        "transformer": "drizzle-zod-date-v1",
        "where": "owner_id = $1"
      },
      "digest": "sha256:5755279834d96978f10b2916578c317bd2e20fe9b984d1de31a2bdfed6c0d036",
      "sourceDigest": "sha256:567940605a669d7d71e16a36bfff26098190598966387f9b2a8a1a4581506c4a"
    }
  }
} as const;
