[package]
name              = "document-hierarchy"
publish.workspace = true

authors.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true
version.workspace    = true

[dependencies]
chrono.workspace                = true
deunicode.workspace             = true
indextree.workspace             = true
quick-xml.workspace             = true
rayon                           = { workspace = true, optional = true }
regex                           = "1"
serde.workspace                 = true
thiserror.workspace             = true
unicode-normalization.workspace = true
htmd                            = "0.5"

[dev-dependencies]
insta    = { version = "1.40", features = ["yaml"] }
tempfile = "3"

[features]
default  = []
parallel = ["indextree/par_iter", "dep:rayon"]
