[package]
name = "document-hierarchy"

autobenches       = false
publish.workspace = true

authors.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true
version.workspace    = true

[lib]
bench = false

[dependencies]
chrono.workspace                = true
deunicode.workspace             = true
htmd                            = "0.5"
indextree.workspace             = true
parser-macros                   = { path = "../parser-macros" }
quick-xml.workspace             = true
rayon                           = { workspace = true, optional = true }
serde.workspace                 = true
smallvec.workspace              = true
smol_str.workspace              = true
thiserror.workspace             = true
unicode-normalization.workspace = true

[dev-dependencies]
criterion.workspace = true
gungraun.workspace  = true
insta               = { version = "1.40", features = ["yaml"] }
tempfile            = "3"

[[bench]]
harness = false
name    = "parser_criterion"

[[bench]]
harness = false
name    = "parser_gungraun"

[features]
default  = []
parallel = ["indextree/par_iter", "dep:rayon"]
