/**
 * Writes `src/catalog.generated.ts` from models.dev.
 *
 *   bun run models:generate
 *
 * Reads the hand-picked models in `src/picks.ts`, looks each one up under
 * models.dev's OpenRouter provider, and emits them as literal-typed data with
 * their capabilities, limits and prices, plus every lab's logo as SVG paths.
 * It also emits `Slug` and `Provider`, the unions `picks.ts` is typed against,
 * so the next pick is checked against what models.dev lists today.
 *
 * Anything it cannot vouch for stops the run: a pick models.dev does not
 * list, a logo that is missing or is not a plain filled path in
 * `currentColor`. The last good catalog stays in place until it succeeds.
 */
import { labs, picks } from '../src/picks';

const API = 'https://models.dev/api.json';
const LOGO = (id: string) => `https://models.dev/logos/${id}.svg`;
const OUT = new URL('../src/catalog.generated.ts', import.meta.url);

type Entry = {
  id: string;
  name: string;
  description?: string;
  family?: string;
  reasoning?: boolean;
  tool_call?: boolean;
  open_weights?: boolean;
  release_date?: string;
  knowledge?: string;
  modalities?: { input?: string[] };
  limit?: { context?: number; output?: number };
  cost?: { input?: number; output?: number };
};

type Registry = Record<string, { models?: Record<string, Entry> }>;

function fail(message: string): never {
  console.error(`models:generate: ${message}`);
  process.exit(1);
}

const registry = (await fetch(API).then((res) => {
  if (!res.ok) fail(`${API} answered ${res.status}`);
  return res.json();
})) as Registry;

const served = registry.openrouter?.models ?? fail('models.dev has no openrouter provider');

const ids = picks.map((pick) => pick.id);
const twice = ids.find((id, index) => ids.indexOf(id) !== index);
if (twice) fail(`${twice} is picked twice`);

const models = picks.map((pick) => {
  const entry = served[pick.id] ?? fail(`${pick.id} is not served by OpenRouter on models.dev`);
  const inputs = entry.modalities?.input ?? ['text'];
  const blurb =
    ('blurb' in pick ? pick.blurb : entry.description) ?? fail(`${pick.id} needs a blurb`);

  return {
    id: pick.id,
    name: 'name' in pick ? pick.name : entry.name,
    lab: pick.id.split('/')[0],
    blurb,
    favorite: 'favorite' in pick,
    family: entry.family ?? null,
    released: entry.release_date ?? fail(`${pick.id} has no release date`),
    knowledge: entry.knowledge ?? null,
    reasoning: entry.reasoning ?? false,
    tools: entry.tool_call ?? false,
    vision: inputs.includes('image'),
    documents: inputs.includes('pdf'),
    open: entry.open_weights ?? false,
    context: entry.limit?.context ?? fail(`${pick.id} has no context limit`),
    output: entry.limit?.output ?? null,
    cost: {
      input: entry.cost?.input ?? fail(`${pick.id} has no input price`),
      output: entry.cost?.output ?? fail(`${pick.id} has no output price`),
    },
  };
});

/**
 * A logo as data: its viewBox and the `d` of each path. The picker draws
 * them in `currentColor`, so anything that is not a plain filled path — a
 * stroke, a gradient, a fixed colour — would draw wrong and is refused.
 */
async function logo(id: string) {
  const res = await fetch(LOGO(id));
  if (!res.ok) fail(`no models.dev logo for ${id} (${res.status})`);
  const svg = await res.text();

  const box = svg.match(/viewBox="([^"]+)"/)?.[1] ?? fail(`${id}.svg has no viewBox`);
  const tags = [...svg.matchAll(/<([a-zA-Z]+)/g)].map((match) => match[1]);
  const odd = tags.find((tag) => tag !== 'svg' && tag !== 'path');
  if (odd) fail(`${id}.svg draws a <${odd}>, not only paths`);
  if (/stroke=|fill="(?!currentColor|none)/.test(svg))
    fail(`${id}.svg is not a filled currentColor mark`);

  const paths = [...svg.matchAll(/<path\b[^>]*?\sd="([^"]+)"[^>]*>/g)].map((match) => ({
    d: match[1],
    even: /fill-rule="evenodd"/.test(match[0]),
  }));
  if (!paths.length) fail(`${id}.svg has no paths`);

  return { box, paths };
}

const marks = Object.fromEntries(
  await Promise.all(
    Object.entries(labs).map(async ([lab, spec]) => [
      lab,
      { name: spec.name, ...(await logo(spec.logo)) },
    ]),
  ),
);

const union = (values: Iterable<string>) =>
  [...new Set(values)]
    .toSorted()
    .map((value) => `  | ${JSON.stringify(value)}`)
    .join('\n');

const source = `// Generated by scripts/models.ts from ${API}. Do not edit by hand:
// change src/picks.ts and run \`bun run models:generate\`.

/** Every model slug OpenRouter serves, as models.dev lists it. */
export type Slug =
${union(Object.keys(served))};

/** Every provider models.dev has a page, and so a logo, for. */
export type Provider =
${union(Object.keys(registry))};

/** Each lab's name and mark, as filled paths in \`currentColor\`. */
export const labs = ${JSON.stringify(marks, null, 2)} as const;

/** The picked models, in the order the picker lists them. */
export const catalog = ${JSON.stringify(models, null, 2)} as const;
`;

await Bun.write(OUT, source);
console.log(`models:generate: ${models.length} models from ${Object.keys(labs).length} labs.`);
