//! Core tree data structures and navigation

use std::collections::HashMap;

use indextree::{Arena, NodeId};
use serde::{Deserialize, Serialize};

use crate::error::{DocumentError, Result};

/// Alignment for table columns
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Hash)]
pub enum ColumnAlign {
    /// Left-aligned
    Left,
    /// Center-aligned
    Center,
    /// Right-aligned
    Right,
    /// No alignment specified
    None,
}

/// Semantic types for document nodes
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Hash)]
pub enum NodeKind {
    /// Root document container
    Root,
    /// Section heading with level (1-6)
    Section {
        /// Heading level (H1 = 1, H6 = 6)
        level: u8,
        /// Section title
        title: String,
    },
    /// Paragraph block
    Paragraph,
    /// List container
    List {
        /// true for numbered, false for bulleted
        ordered: bool,
        /// true if compact (no blank lines between items)
        tight: bool,
    },
    /// List item
    ListItem,
    /// Code block
    CodeBlock {
        /// Programming language identifier
        language: Option<String>,
    },
    /// Block quotation
    BlockQuote,
    /// Table container
    Table {
        /// Column alignments
        alignments: Vec<ColumnAlign>,
    },
    /// Table row
    TableRow,
    /// Table cell
    TableCell,
    /// Inline text
    Text(String),
    /// Strong emphasis (bold)
    Strong,
    /// Emphasis (italic)
    Emphasis,
    /// Hyperlink
    Link {
        /// URL destination
        url: String,
        /// Optional title attribute
        title: Option<String>,
    },
    /// Image
    Image {
        /// Source URL
        url: String,
        /// Alt text
        alt: String,
    },
    /// Horizontal rule
    ThematicBreak,
}

/// A node in the document tree
///
/// # Examples
///
/// ```
/// use pdf_hierarchy::{DocumentNode, NodeKind};
///
/// let section = DocumentNode::section(1, "Introduction");
/// assert!(section.is_section());
/// assert_eq!(section.anchor, Some("introduction".to_string()));
/// ```
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DocumentNode {
    /// Semantic type of this node
    pub kind: NodeKind,
    /// Stable anchor ID for linking (e.g., "introduction")
    pub anchor: Option<String>,
    /// Source position in original text (start, end)
    pub source_pos: Option<(usize, usize)>,
    /// Original PDF page number if available
    pub page_hint: Option<u32>,
    /// Text content of this node
    pub content: String,
}

impl DocumentNode {
    /// Create a new node with given kind and content
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentNode, NodeKind};
    ///
    /// let node = DocumentNode::new(NodeKind::Paragraph, "Hello world");
    /// assert_eq!(node.content, "Hello world");
    /// assert!(node.anchor.is_none());
    /// ```
    pub fn new(kind: NodeKind, content: impl Into<String>) -> Self {
        Self { kind, anchor: None, source_pos: None, page_hint: None, content: content.into() }
    }

    /// Create a section node with auto-generated anchor
    ///
    /// The anchor is generated by slugifying the title (lowercase,
    /// non-alphanumeric to hyphens).
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::DocumentNode;
    ///
    /// let sec = DocumentNode::section(2, "Getting Started");
    /// assert_eq!(sec.anchor, Some("getting-started".to_string()));
    /// assert!(matches!(sec.kind, pdf_hierarchy::NodeKind::Section { level: 2, .. }));
    /// ```
    pub fn section(level: u8, title: impl AsRef<str>) -> Self {
        let title = title.as_ref();
        Self {
            kind: NodeKind::Section { level, title: title.to_string() },
            anchor: Some(Self::slugify(title)),
            source_pos: None,
            page_hint: None,
            content: title.to_string(),
        }
    }

    /// Generate URL-safe slug from text
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::DocumentNode;
    ///
    /// assert_eq!(DocumentNode::slugify("Hello World!"), "hello-world");
    /// assert_eq!(DocumentNode::slugify("Section 1.2.3"), "section-1-2-3");
    /// assert_eq!(DocumentNode::slugify("--trim--me--"), "trim-me");
    /// ```
    pub fn slugify(text: &str) -> String {
        text.to_lowercase()
            .replace(|c: char| !c.is_alphanumeric() && c != ' ', "-")
            .split('-')
            .filter(|s| !s.is_empty())
            .collect::<Vec<_>>()
            .join("-")
    }

    /// Check if this node is a section (heading)
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentNode, NodeKind};
    ///
    /// assert!(DocumentNode::section(1, "Title").is_section());
    /// assert!(!DocumentNode::new(NodeKind::Paragraph, "text").is_section());
    /// ```
    pub fn is_section(&self) -> bool {
        matches!(self.kind, NodeKind::Section { .. })
    }

    /// Get section level if this is a section, None otherwise
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::DocumentNode;
    ///
    /// let h1 = DocumentNode::section(1, "Title");
    /// assert_eq!(h1.section_level(), Some(1));
    ///
    /// let h3 = DocumentNode::section(3, "Deep");
    /// assert_eq!(h3.section_level(), Some(3));
    /// ```
    pub fn section_level(&self) -> Option<u8> {
        match &self.kind {
            NodeKind::Section { level, .. } => Some(*level),
            _ => None,
        }
    }
}

/// Hierarchical document tree with dual indexing
///
/// Stores nodes in an arena for cache efficiency and maintains
/// both hierarchical paths and named anchors for navigation.
///
/// # Type Parameters
///
/// Uses `indextree::Arena` internally, so NodeIds are valid for the
/// lifetime of the DocumentTree.
pub struct DocumentTree {
    arena: Arena<DocumentNode>,
    root: NodeId,
    anchor_index: HashMap<String, NodeId>,
}

impl DocumentTree {
    /// Create a new empty document tree with a root node
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::DocumentTree;
    ///
    /// let tree = DocumentTree::new();
    /// assert_eq!(tree.hierarchical_path(tree.root()), "root");
    /// ```
    pub fn new() -> Self {
        let mut arena = Arena::new();
        let root = arena.new_node(DocumentNode {
            kind: NodeKind::Root,
            anchor: Some("root".to_string()),
            source_pos: None,
            page_hint: None,
            content: String::new(),
        });

        Self { arena, root, anchor_index: HashMap::new() }
    }

    /// Get the root node ID
    pub fn root(&self) -> NodeId {
        self.root
    }

    /// Access the underlying arena (advanced usage)
    pub fn arena(&self) -> &Arena<DocumentNode> {
        &self.arena
    }

    /// Access mutable arena (careful: breaks invariants if misused)
    pub fn arena_mut(&mut self) -> &mut Arena<DocumentNode> {
        &mut self.arena
    }

    /// Get reference to node data by ID
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentTree, DocumentNode, NodeKind};
    ///
    /// let mut tree = DocumentTree::new();
    /// let child = tree.add_child(tree.root(), DocumentNode::new(NodeKind::Paragraph, "test"));
    /// assert_eq!(tree.get(child).unwrap().content, "test");
    /// ```
    pub fn get(&self, id: NodeId) -> Option<&DocumentNode> {
        self.arena.get(id).map(|n| n.get())
    }

    /// Get mutable reference to node data
    pub fn get_mut(&mut self, id: NodeId) -> Option<&mut DocumentNode> {
        self.arena.get_mut(id).map(|n| n.get_mut())
    }

    /// Add a child node to a parent, updating anchor index
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentTree, DocumentNode};
    ///
    /// let mut tree = DocumentTree::new();
    /// let section = DocumentNode::section(1, "Intro");
    /// let id = tree.add_child(tree.root(), section);
    ///
    /// assert!(tree.find_by_anchor("intro").is_some());
    /// ```
    pub fn add_child(&mut self, parent: NodeId, node: DocumentNode) -> NodeId {
        let anchor = node.anchor.clone();
        let id = self.arena.new_node(node);
        parent.append(id, &mut self.arena);

        if let Some(a) = anchor {
            self.anchor_index.insert(a, id);
        }

        id
    }

    /// Find node by anchor (O(1) lookup)
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentTree, DocumentNode};
    ///
    /// let mut tree = DocumentTree::new();
    /// let node = DocumentNode::section(1, "Methodology");
    /// tree.add_child(tree.root(), node);
    ///
    /// let found = tree.find_by_anchor("methodology");
    /// assert!(found.is_some());
    /// ```
    pub fn find_by_anchor(&self, anchor: &str) -> Option<NodeId> {
        self.anchor_index.get(anchor).copied()
    }

    /// Get anchor string for a node if it has one
    pub fn get_anchor(&self, id: NodeId) -> Option<&str> {
        self.get(id).and_then(|n| n.anchor.as_deref())
    }

    /// Generate hierarchical path string (e.g., "1.2.3")
    ///
    /// Returns "root" for the root node.
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentTree, DocumentNode, NodeKind};
    ///
    /// let mut tree = DocumentTree::new();
    /// let sec1 = tree.add_child(tree.root(), DocumentNode::section(1, "A"));
    /// let sec2 = tree.add_child(sec1, DocumentNode::section(2, "B"));
    ///
    /// assert_eq!(tree.hierarchical_path(sec1), "1");
    /// assert_eq!(tree.hierarchical_path(sec2), "1.1");
    /// ```
    pub fn hierarchical_path(&self, id: NodeId) -> String {
        let mut indices = Vec::new();
        let mut current = id;

        while let Some(parent) = current.parent(&self.arena) {
            let idx = parent.children(&self.arena).position(|c| c == current).unwrap_or(0);
            indices.push(idx + 1);
            current = parent;
        }

        indices.reverse();

        if indices.is_empty() {
            "root".to_string()
        } else {
            indices.iter().map(|n| n.to_string()).collect::<Vec<_>>().join(".")
        }
    }

    /// Get path as zero-indexed vector (useful for sorting)
    pub fn path_vec(&self, id: NodeId) -> Vec<usize> {
        let mut indices = Vec::new();
        let mut current = id;

        while let Some(parent) = current.parent(&self.arena) {
            let idx = parent.children(&self.arena).position(|c| c == current).unwrap_or(0);
            indices.push(idx);
            current = parent;
        }

        indices.reverse();
        indices
    }

    /// Iterate all descendants of a node (pre-order)
    pub fn descendants(&self, node: NodeId) -> impl Iterator<Item = NodeId> + '_ {
        node.descendants(&self.arena)
    }

    /// Iterate ancestors from immediate parent to root
    pub fn ancestors(&self, node: NodeId) -> impl Iterator<Item = NodeId> + '_ {
        node.ancestors(&self.arena)
    }

    /// Iterate immediate children
    pub fn children(&self, node: NodeId) -> impl Iterator<Item = NodeId> + '_ {
        node.children(&self.arena)
    }

    /// Get all sections (headings) with (id, anchor, path, level)
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentTree, DocumentNode};
    ///
    /// let mut tree = DocumentTree::new();
    /// tree.add_child(tree.root(), DocumentNode::section(1, "First"));
    /// let sec = tree.add_child(tree.root(), DocumentNode::section(2, "Second"));
    /// tree.add_child(sec, DocumentNode::section(3, "Nested"));
    ///
    /// let sections = tree.sections();
    /// assert_eq!(sections.len(), 3);
    /// ```
    pub fn sections(&self) -> Vec<(NodeId, String, String, u8)> {
        self.descendants(self.root)
            .filter_map(|id| {
                let node = self.get(id)?;
                if let NodeKind::Section { level, .. } = &node.kind {
                    let path = self.hierarchical_path(id);
                    let anchor = node.anchor.clone().unwrap_or_default();
                    Some((id, anchor, path, *level))
                } else {
                    None
                }
            })
            .collect()
    }

    /// Find node by hierarchical path "1.2.3"
    ///
    /// # Errors
    ///
    /// Returns Err if path format is invalid
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentTree, DocumentNode};
    ///
    /// let mut tree = DocumentTree::new();
    /// let sec = tree.add_child(tree.root(), DocumentNode::section(1, "A"));
    ///
    /// assert_eq!(tree.find_by_path("1").unwrap(), sec);
    /// assert!(tree.find_by_path("invalid").is_err());
    /// ```
    pub fn find_by_path(&self, path: &str) -> Result<NodeId> {
        if path == "root" {
            return Ok(self.root);
        }

        let parts: Vec<usize> = path
            .split('.')
            .map(|s| s.parse::<usize>())
            .collect::<std::result::Result<Vec<_>, _>>()
            .map_err(|_| DocumentError::InvalidPath(path.to_string()))?;

        if parts.is_empty() {
            return Ok(self.root);
        }

        let mut current = self.root;
        for idx in parts {
            if idx == 0 {
                return Err(DocumentError::InvalidPath("path indices are 1-based".to_string()));
            }
            let children: Vec<NodeId> = current.children(&self.arena).collect();
            if idx > children.len() {
                return Err(DocumentError::InvalidPath(format!("index {} out of bounds", idx)));
            }
            current = children[idx - 1];
        }
        Ok(current)
    }

    /// Get nearest parent that is a section
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentTree, DocumentNode, NodeKind};
    ///
    /// let mut tree = DocumentTree::new();
    /// let sec = tree.add_child(tree.root(), DocumentNode::section(1, "Parent"));
    /// let para = tree.add_child(sec, DocumentNode::new(NodeKind::Paragraph, "text"));
    ///
    /// assert_eq!(tree.parent_section(para).unwrap(), sec);
    /// ```
    pub fn parent_section(&self, id: NodeId) -> Option<NodeId> {
        self.ancestors(id).find(|&aid| self.get(aid).map(|n| n.is_section()).unwrap_or(false))
    }

    /// Extract all text content from a subtree
    pub fn extract_text(&self, id: NodeId) -> String {
        let mut parts = Vec::new();
        for node_id in id.descendants(&self.arena) {
            if let Some(node) = self.get(node_id) {
                match &node.kind {
                    NodeKind::Text(text) => parts.push(text.as_str()),
                    NodeKind::Section { title, .. } => parts.push(title.as_str()),
                    _ => {
                        if !node.content.is_empty() {
                            parts.push(&node.content);
                        }
                    }
                }
            }
        }
        parts.join(" ")
    }

    /// Debug representation of tree structure
    pub fn debug_tree(&self) -> String {
        let mut output = String::new();
        self.debug_node(self.root, 0, &mut output);
        output
    }

    fn debug_node(&self, id: NodeId, depth: usize, output: &mut String) {
        let indent = "  ".repeat(depth);
        if let Some(node) = self.get(id) {
            let path = self.hierarchical_path(id);
            let anchor_display =
                node.anchor.as_ref().map(|a| format!("[#{}]", a)).unwrap_or_default();

            match &node.kind {
                NodeKind::Section { title, level } => {
                    output.push_str(&format!(
                        "{}[{}]{} H{}: {}\n",
                        indent, path, anchor_display, level, title
                    ));
                }
                NodeKind::Paragraph if !node.content.is_empty() => {
                    let preview = if node.content.len() > 40 {
                        format!("{}...", &node.content[..40])
                    } else {
                        node.content.clone()
                    };
                    output.push_str(&format!(
                        "{}[{}]{} P: {}\n",
                        indent, path, anchor_display, preview
                    ));
                }
                _ => {
                    output.push_str(&format!(
                        "{}[{}]{} {:?}\n",
                        indent,
                        path,
                        anchor_display,
                        std::mem::discriminant(&node.kind)
                    ));
                }
            }

            for child in id.children(&self.arena) {
                self.debug_node(child, depth + 1, output);
            }
        }
    }
}

impl Default for DocumentTree {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_slugify() {
        assert_eq!(DocumentNode::slugify("Hello World"), "hello-world");
        assert_eq!(DocumentNode::slugify("Section 1.2.3"), "section-1-2-3");
        assert_eq!(DocumentNode::slugify("  Trim  Me  "), "trim-me");
        assert_eq!(DocumentNode::slugify("UPPERCASE"), "uppercase");
    }

    #[test]
    fn test_section_creation() {
        let sec = DocumentNode::section(2, "Getting Started");
        assert!(sec.is_section());
        assert_eq!(sec.section_level(), Some(2));
        assert_eq!(sec.anchor, Some("getting-started".to_string()));
        assert_eq!(sec.content, "Getting Started");
    }

    #[test]
    fn test_tree_construction() {
        let mut tree = DocumentTree::new();
        let root = tree.root();

        let sec1 = tree.add_child(root, DocumentNode::section(1, "Introduction"));
        let sec2 = tree.add_child(root, DocumentNode::section(1, "Methods"));
        let subsec = tree.add_child(sec2, DocumentNode::section(2, "Participants"));

        assert_eq!(tree.hierarchical_path(sec1), "1");
        assert_eq!(tree.hierarchical_path(sec2), "2");
        assert_eq!(tree.hierarchical_path(subsec), "2.1");
    }

    #[test]
    fn test_anchor_lookup() {
        let mut tree = DocumentTree::new();
        tree.add_child(tree.root(), DocumentNode::section(1, "Introduction"));
        tree.add_child(tree.root(), DocumentNode::section(1, "Results"));

        assert!(tree.find_by_anchor("introduction").is_some());
        assert!(tree.find_by_anchor("results").is_some());
        assert!(tree.find_by_anchor("nonexistent").is_none());
    }

    #[test]
    fn test_path_navigation() {
        let mut tree = DocumentTree::new();
        let sec1 = tree.add_child(tree.root(), DocumentNode::section(1, "A"));
        let sec2 = tree.add_child(sec1, DocumentNode::section(2, "B"));

        assert_eq!(tree.find_by_path("1").unwrap(), sec1);
        assert_eq!(tree.find_by_path("1.1").unwrap(), sec2);
        assert!(tree.find_by_path("1.2").is_err());
        assert!(tree.find_by_path("invalid").is_err());
    }

    #[test]
    fn test_parent_section() {
        let mut tree = DocumentTree::new();
        let section = tree.add_child(tree.root(), DocumentNode::section(1, "Parent"));
        let paragraph = tree.add_child(section, DocumentNode::new(NodeKind::Paragraph, "text"));

        assert_eq!(tree.parent_section(paragraph).unwrap(), section);
        assert!(tree.parent_section(section).is_none()); // Parent is root, not a section
    }

    #[test]
    fn test_sections_list() {
        let mut tree = DocumentTree::new();
        tree.add_child(tree.root(), DocumentNode::section(1, "First"));
        let sec = tree.add_child(tree.root(), DocumentNode::section(1, "Second"));
        tree.add_child(sec, DocumentNode::section(2, "Nested"));

        let sections = tree.sections();
        assert_eq!(sections.len(), 3);

        // Check ordering (pre-order)
        assert_eq!(sections[0].1, "first");
        assert_eq!(sections[1].1, "second");
        assert_eq!(sections[2].1, "nested");
    }
}
