//! Core tree data structures and navigation

use std::collections::HashMap;
use std::fmt;
use std::fmt::Write;
use std::ops::{Index, Range};

use deunicode::deunicode;
use indextree::{Arena, NodeId};
use serde::{Deserialize, Serialize};
use unicode_normalization::UnicodeNormalization;

use crate::error::{DocumentError, Result};

/// Alignment for table columns
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Hash)]
pub enum ColumnAlign {
    /// Left-aligned
    Left,
    /// Center-aligned
    Center,
    /// Right-aligned
    Right,
}

pub type ColumnAlignment = Option<ColumnAlign>;

/// Semantic types for document nodes
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Hash)]
pub enum NodeKind {
    /// Root document container
    Root,
    /// Section heading with level (1-6)
    Section {
        /// Heading level (H1 = 1, H6 = 6)
        level: u8,
    },
    /// Paragraph block
    Paragraph,
    /// List container
    List {
        /// true for numbered, false for bulleted
        ordered: bool,
        /// true if compact (no blank lines between items)
        tight: bool,
    },
    /// List item
    ListItem,
    /// Code block
    CodeBlock,
    /// Block quotation
    BlockQuote,
    /// Table container
    Table,
    /// Table row
    TableRow,
    /// Table cell
    TableCell,
    /// Inline text
    Text,
    /// Strong emphasis (bold)
    Strong,
    /// Emphasis (italic)
    Emphasis,
    /// Hyperlink
    Link,
    /// Image
    Image,
    /// Horizontal rule
    ThematicBreak,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum NodeMeta {
    Link { url: String, title: Option<String> },
    Image { url: String, alt: String },
    CodeBlock { language: Option<String> },
    Table { alignments: Vec<ColumnAlignment> },
}

/// A node in the document tree
///
/// # Examples
///
/// ```
/// use pdf_hierarchy::{DocumentNode, NodeKind};
///
/// let section = DocumentNode::section(1, "Introduction");
/// assert!(section.is_section());
/// assert_eq!(section.anchor, Some("introduction".to_string()));
/// ```
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DocumentNode {
    /// Semantic type of this node
    pub kind: NodeKind,
    /// Stable anchor ID for linking (e.g., "introduction")
    pub anchor: Option<String>,
    pub source_pos: Option<Range<usize>>,
    /// Original source page number if available
    pub page_hint: Option<u32>,
    /// Text content of this node
    pub content: String,
    pub meta: Option<NodeMeta>,
}

impl DocumentNode {
    /// Create a new node with given kind and content
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentNode, NodeKind};
    ///
    /// let node = DocumentNode::new(NodeKind::Paragraph, "Hello world");
    /// assert_eq!(node.content, "Hello world");
    /// assert!(node.anchor.is_none());
    /// ```
    #[must_use]
    pub fn new(kind: NodeKind, content: impl Into<String>) -> Self {
        Self {
            kind,
            anchor: None,
            source_pos: None,
            page_hint: None,
            content: content.into(),
            meta: None,
        }
    }

    /// Create a link node with URL/title metadata and visible content.
    #[must_use]
    pub fn link(url: impl Into<String>, title: Option<String>, content: impl Into<String>) -> Self {
        Self {
            kind: NodeKind::Link,
            anchor: None,
            source_pos: None,
            page_hint: None,
            content: content.into(),
            meta: Some(NodeMeta::Link { url: url.into(), title }),
        }
    }

    /// Create an image node from source URL and alt text.
    #[must_use]
    pub fn image(url: impl Into<String>, alt: impl Into<String>) -> Self {
        let alt = alt.into();
        Self {
            kind: NodeKind::Image,
            anchor: None,
            source_pos: None,
            page_hint: None,
            content: alt.clone(),
            meta: Some(NodeMeta::Image { url: url.into(), alt }),
        }
    }

    /// Create a section node with auto-generated anchor
    ///
    /// The anchor is generated by slugifying the title (lowercase,
    /// non-alphanumeric to hyphens).
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::DocumentNode;
    ///
    /// let sec = DocumentNode::section(2, "Getting Started");
    /// assert_eq!(sec.anchor, Some("getting-started".to_string()));
    /// assert!(matches!(sec.kind, pdf_hierarchy::NodeKind::Section { level: 2, .. }));
    /// ```
    #[must_use]
    pub fn section(level: u8, title: impl AsRef<str>) -> Self {
        let title = title.as_ref();
        Self {
            kind: NodeKind::Section { level },
            anchor: Some(Self::slugify(title)),
            source_pos: None,
            page_hint: None,
            content: title.to_string(),
            meta: None,
        }
    }

    /// Generate URL-safe slug from text
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::DocumentNode;
    ///
    /// assert_eq!(DocumentNode::slugify("Hello World!"), "hello-world");
    /// assert_eq!(DocumentNode::slugify("Section 1.2.3"), "section-1-2-3");
    /// assert_eq!(DocumentNode::slugify("--trim--me--"), "trim-me");
    /// ```
    #[must_use]
    pub fn slugify(text: &str) -> String {
        Self::slug(text.nfkc().flat_map(char::to_lowercase))
    }

    /// Generate an ASCII-transliterated URL-safe slug from text.
    #[must_use]
    pub fn slugify_ascii(text: &str) -> String {
        Self::slug(deunicode(text).chars().flat_map(char::to_lowercase))
    }

    fn slug(iter: impl Iterator<Item = char>) -> String {
        let mut out = String::new();
        let mut dash = false;
        for ch in iter {
            if ch.is_alphanumeric() {
                out.push(ch);
                dash = false;
                continue;
            }
            if out.is_empty() || dash {
                continue;
            }
            out.push('-');
            dash = true;
        }
        if out.ends_with('-') {
            out.pop();
        }
        out
    }

    /// Check if this node is a section (heading)
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentNode, NodeKind};
    ///
    /// assert!(DocumentNode::section(1, "Title").is_section());
    /// assert!(!DocumentNode::new(NodeKind::Paragraph, "text").is_section());
    /// ```
    #[inline]
    pub fn is_section(&self) -> bool {
        matches!(self.kind, NodeKind::Section { .. })
    }

    /// Return section title when this node is a section.
    #[inline]
    pub fn section_title(&self) -> Option<&str> {
        self.is_section().then_some(self.content.as_str())
    }

    /// Get section level if this is a section, None otherwise
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::DocumentNode;
    ///
    /// let h1 = DocumentNode::section(1, "Title");
    /// assert_eq!(h1.section_level(), Some(1));
    ///
    /// let h3 = DocumentNode::section(3, "Deep");
    /// assert_eq!(h3.section_level(), Some(3));
    /// ```
    #[inline]
    pub fn section_level(&self) -> Option<u8> {
        match self.kind {
            NodeKind::Section { level } => Some(level),
            _ => None,
        }
    }

    /// Return link URL when this node is a link.
    #[inline]
    pub fn link_url(&self) -> Option<&str> {
        if !matches!(self.kind, NodeKind::Link) {
            return None;
        }
        match &self.meta {
            Some(NodeMeta::Link { url, .. }) => Some(url.as_str()),
            _ => None,
        }
    }

    /// Return image URL when this node is an image.
    #[inline]
    pub fn image_url(&self) -> Option<&str> {
        if !matches!(self.kind, NodeKind::Image) {
            return None;
        }
        match &self.meta {
            Some(NodeMeta::Image { url, .. }) => Some(url.as_str()),
            _ => None,
        }
    }
}

/// Hierarchical document tree with dual indexing
///
/// Stores nodes in an arena for cache efficiency and maintains
/// both hierarchical paths and named anchors for navigation.
///
/// # Type Parameters
///
/// Uses `indextree::Arena` internally, so NodeIds are valid for the
/// lifetime of the DocumentTree.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DocumentTree {
    arena: Arena<DocumentNode>,
    root: NodeId,
    index: HashMap<String, NodeId>,
    alias: HashMap<String, NodeId>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SectionEntry {
    pub id: NodeId,
    pub anchor: String,
    pub path: String,
    pub level: u8,
}

impl DocumentTree {
    /// Create a new empty document tree with a root node
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::DocumentTree;
    ///
    /// let tree = DocumentTree::new();
    /// assert_eq!(tree.hierarchical_path(tree.root()), "root");
    /// ```
    #[must_use]
    pub fn new() -> Self {
        let mut arena = Arena::new();
        let root = arena.new_node(DocumentNode {
            kind: NodeKind::Root,
            anchor: Some("root".to_string()),
            source_pos: None,
            page_hint: None,
            content: String::new(),
            meta: None,
        });

        Self { arena, root, index: HashMap::new(), alias: HashMap::new() }
    }

    /// Get the root node ID
    #[inline]
    pub fn root(&self) -> NodeId {
        self.root
    }

    /// Access the underlying arena (advanced usage)
    pub fn arena(&self) -> &Arena<DocumentNode> {
        &self.arena
    }

    /// Return total nodes currently stored in the arena.
    #[inline]
    pub fn node_count(&self) -> usize {
        self.arena.count()
    }

    /// Mutable arena access for advanced operations.
    ///
    /// Caller is responsible for calling `rebuild_index` if anchors change.
    pub fn arena_mut_unchecked(&mut self) -> &mut Arena<DocumentNode> {
        &mut self.arena
    }

    /// Rebuild anchor indexes from current arena contents.
    pub fn rebuild_index(&mut self) {
        self.index.clear();
        self.alias.clear();
        let ids = self.root.descendants(&self.arena).collect::<Vec<_>>();
        for id in ids {
            let anchor = self.get(id).and_then(|n| n.anchor.clone());
            if let Some(anchor) = anchor {
                self.put_anchor(id, &anchor);
            }
        }
    }

    /// Get reference to node data by ID
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentTree, DocumentNode, NodeKind};
    ///
    /// let mut tree = DocumentTree::new();
    /// let child = tree.add_child(tree.root(), DocumentNode::new(NodeKind::Paragraph, "test"));
    /// assert_eq!(tree.get(child).unwrap().content, "test");
    /// ```
    pub fn get(&self, id: NodeId) -> Option<&DocumentNode> {
        self.arena.get(id).map(|n| n.get())
    }

    /// Set node anchor while keeping indexes consistent.
    ///
    /// Returns `false` when `id` is not present in this tree.
    #[must_use]
    pub fn set_anchor(&mut self, id: NodeId, anchor: Option<String>) -> bool {
        let (old, new) = {
            let Some(node) = self.arena.get_mut(id).map(|n| n.get_mut()) else {
                return false;
            };
            let old = node.anchor.take();
            node.anchor = anchor;
            let new = node.anchor.clone();
            (old, new)
        };

        if let Some(old) = old {
            self.drop_anchor(id, &old);
        }
        if let Some(new) = new {
            self.put_anchor(id, &new);
        }
        true
    }

    /// Mutate a node and re-sync anchor indexes when anchor changes.
    ///
    /// Returns `false` when `id` is not present in this tree.
    #[must_use]
    pub fn update<F>(&mut self, id: NodeId, f: F) -> bool
    where
        F: FnOnce(&mut DocumentNode),
    {
        let (old, new) = {
            let Some(node) = self.arena.get_mut(id).map(|n| n.get_mut()) else {
                return false;
            };
            let old = node.anchor.clone();
            f(node);
            if old.as_ref() == node.anchor.as_ref() {
                return true;
            }
            let new = node.anchor.clone();
            (old, new)
        };

        if old == new {
            return true;
        }
        if let Some(old) = old {
            self.drop_anchor(id, &old);
        }
        if let Some(new) = new {
            self.put_anchor(id, &new);
        }
        true
    }

    /// Add a child node to a parent, updating anchor index
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentTree, DocumentNode};
    ///
    /// let mut tree = DocumentTree::new();
    /// let section = DocumentNode::section(1, "Intro");
    /// let id = tree.add_child(tree.root(), section);
    ///
    /// assert!(tree.find_by_anchor("intro").is_some());
    /// ```
    pub fn add_child(&mut self, parent: NodeId, node: DocumentNode) -> NodeId {
        let anchor = node.anchor.clone();
        let id = self.arena.new_node(node);
        parent.append(id, &mut self.arena);

        if let Some(anchor) = anchor {
            self.put_anchor(id, &anchor);
        }

        id
    }

    /// Find node by anchor.
    ///
    /// Tries exact match, then Unicode-normalized slug, then
    /// ASCII-transliterated slug. Each form is checked against
    /// both the primary index and the alias map.
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentTree, DocumentNode};
    ///
    /// let mut tree = DocumentTree::new();
    /// let node = DocumentNode::section(1, "Methodology");
    /// tree.add_child(tree.root(), node);
    ///
    /// let found = tree.find_by_anchor("methodology");
    /// assert!(found.is_some());
    /// ```
    #[must_use]
    pub fn find_by_anchor(&self, query: &str) -> Option<NodeId> {
        let lookup = |key: &str| self.index.get(key).or_else(|| self.alias.get(key)).copied();

        if let Some(id) = lookup(query) {
            return Some(id);
        }

        let slug = DocumentNode::slugify(query);
        if slug != query
            && let Some(id) = lookup(&slug)
        {
            return Some(id);
        }

        let ascii = DocumentNode::slugify_ascii(query);
        if ascii != query && ascii != slug {
            return lookup(&ascii);
        }

        None
    }

    /// Get anchor string for a node if it has one
    pub fn get_anchor(&self, id: NodeId) -> Option<&str> {
        self.get(id).and_then(|n| n.anchor.as_deref())
    }

    fn put_anchor(&mut self, id: NodeId, anchor: &str) {
        self.index.entry(anchor.to_string()).or_insert(id);
        let alias = DocumentNode::slugify_ascii(anchor);
        if alias != anchor {
            self.alias.entry(alias).or_insert(id);
        }
    }

    fn drop_anchor(&mut self, id: NodeId, anchor: &str) {
        if self.index.get(anchor) == Some(&id) {
            self.index.remove(anchor);
        }
        let alias = DocumentNode::slugify_ascii(anchor);
        if self.alias.get(&alias) == Some(&id) {
            self.alias.remove(&alias);
        }
    }

    fn child_indices(&self, id: NodeId) -> Vec<usize> {
        let mut out = Vec::new();
        let mut current = id;
        while let Some(parent) = self.arena[current].parent() {
            let idx = parent.children(&self.arena).position(|child| child == current).unwrap_or(0);
            out.push(idx);
            current = parent;
        }
        out.reverse();
        out
    }

    /// Generate hierarchical path string (e.g., "1.2.3")
    ///
    /// Returns "root" for the root node.
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentTree, DocumentNode, NodeKind};
    ///
    /// let mut tree = DocumentTree::new();
    /// let sec1 = tree.add_child(tree.root(), DocumentNode::section(1, "A"));
    /// let sec2 = tree.add_child(sec1, DocumentNode::section(2, "B"));
    ///
    /// assert_eq!(tree.hierarchical_path(sec1), "1");
    /// assert_eq!(tree.hierarchical_path(sec2), "1.1");
    /// ```
    #[must_use]
    pub fn hierarchical_path(&self, id: NodeId) -> String {
        let indices = self.child_indices(id);
        if indices.is_empty() {
            "root".to_string()
        } else {
            indices.iter().map(|n| (n + 1).to_string()).collect::<Vec<_>>().join(".")
        }
    }

    /// Get path as zero-indexed vector (useful for sorting)
    #[must_use]
    pub fn path_vec(&self, id: NodeId) -> Vec<usize> {
        self.child_indices(id)
    }

    /// Iterate all descendants of a node (pre-order)
    pub fn descendants(&self, node: NodeId) -> impl Iterator<Item = NodeId> + '_ {
        node.descendants(&self.arena)
    }

    /// Iterate ancestors from immediate parent to root
    pub fn ancestors(&self, node: NodeId) -> impl Iterator<Item = NodeId> + '_ {
        node.ancestors(&self.arena)
    }

    /// Iterate immediate children
    pub fn children(&self, node: NodeId) -> impl Iterator<Item = NodeId> + '_ {
        node.children(&self.arena)
    }

    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentTree, DocumentNode};
    ///
    /// let mut tree = DocumentTree::new();
    /// tree.add_child(tree.root(), DocumentNode::section(1, "First"));
    /// let sec = tree.add_child(tree.root(), DocumentNode::section(2, "Second"));
    /// tree.add_child(sec, DocumentNode::section(3, "Nested"));
    ///
    /// let sections = tree.sections();
    /// assert_eq!(sections.len(), 3);
    /// ```
    #[must_use]
    pub fn sections(&self) -> Vec<SectionEntry> {
        self.descendants(self.root)
            .filter_map(|id| {
                let node = self.get(id)?;
                if !matches!(node.kind, NodeKind::Section { .. }) {
                    return None;
                }
                Some(SectionEntry {
                    id,
                    anchor: node.anchor.clone().unwrap_or_default(),
                    path: self.hierarchical_path(id),
                    level: node.section_level().unwrap_or(0),
                })
            })
            .collect()
    }

    /// Find node by hierarchical path "1.2.3"
    ///
    /// # Errors
    ///
    /// Returns Err if path format is invalid
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentTree, DocumentNode};
    ///
    /// let mut tree = DocumentTree::new();
    /// let sec = tree.add_child(tree.root(), DocumentNode::section(1, "A"));
    ///
    /// assert_eq!(tree.find_by_path("1").unwrap(), sec);
    /// assert!(tree.find_by_path("invalid").is_err());
    /// ```
    pub fn find_by_path(&self, path: &str) -> Result<NodeId> {
        if path == "root" {
            return Ok(self.root);
        }

        let parts: Vec<usize> = path
            .split('.')
            .map(|s| s.parse::<usize>())
            .collect::<std::result::Result<Vec<_>, _>>()
            .map_err(|_| DocumentError::InvalidPath(path.to_string()))?;

        if parts.is_empty() {
            return Ok(self.root);
        }

        let mut current = self.root;
        for idx in parts {
            if idx == 0 {
                return Err(DocumentError::InvalidPath("path indices are 1-based".to_string()));
            }
            if let Some(child) = current.children(&self.arena).nth(idx - 1) {
                current = child;
                continue;
            }
            return Err(DocumentError::InvalidPath(format!("index {} out of bounds", idx)));
        }
        Ok(current)
    }

    /// Get nearest parent that is a section
    ///
    /// # Examples
    ///
    /// ```
    /// use pdf_hierarchy::{DocumentTree, DocumentNode, NodeKind};
    ///
    /// let mut tree = DocumentTree::new();
    /// let sec = tree.add_child(tree.root(), DocumentNode::section(1, "Parent"));
    /// let para = tree.add_child(sec, DocumentNode::new(NodeKind::Paragraph, "text"));
    ///
    /// assert_eq!(tree.parent_section(para).unwrap(), sec);
    /// ```
    pub fn parent_section(&self, id: NodeId) -> Option<NodeId> {
        self.ancestors(id)
            .skip(1)
            .find(|&aid| self.get(aid).map(|n| n.is_section()).unwrap_or(false))
    }

    /// Extract all text content from a subtree
    pub fn extract_text(&self, id: NodeId) -> String {
        let mut parts = Vec::new();
        for node_id in id.descendants(&self.arena) {
            if let Some(node) = self.get(node_id)
                && !node.content.is_empty()
            {
                parts.push(node.content.as_str());
            }
        }
        parts.join(" ")
    }

    /// Debug representation of tree structure
    pub fn debug_tree(&self) -> String {
        let mut output = String::new();
        self.debug_node(self.root, 0, &mut output);
        output
    }

    fn debug_node(&self, id: NodeId, depth: usize, output: &mut String) {
        let indent = "  ".repeat(depth);
        if let Some(node) = self.get(id) {
            let path = self.hierarchical_path(id);
            let anchor_display =
                node.anchor.as_ref().map(|a| format!("[#{}]", a)).unwrap_or_default();

            match node.kind {
                NodeKind::Section { level } => {
                    let _ = writeln!(
                        output,
                        "{}[{}]{} H{}: {}",
                        indent, path, anchor_display, level, node.content
                    );
                }
                NodeKind::Paragraph if !node.content.is_empty() => {
                    let _ = writeln!(
                        output,
                        "{}[{}]{} P: {}",
                        indent, path, anchor_display, node.content
                    );
                }
                _ => {
                    let _ = writeln!(
                        output,
                        "{}[{}]{} {:?}",
                        indent,
                        path,
                        anchor_display,
                        std::mem::discriminant(&node.kind)
                    );
                }
            }

            for child in id.children(&self.arena) {
                self.debug_node(child, depth + 1, output);
            }
        }
    }
}

impl Default for DocumentTree {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for DocumentTree {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.debug_tree())
    }
}

impl AsRef<Arena<DocumentNode>> for DocumentTree {
    fn as_ref(&self) -> &Arena<DocumentNode> {
        &self.arena
    }
}

impl Index<NodeId> for DocumentTree {
    type Output = DocumentNode;

    fn index(&self, id: NodeId) -> &Self::Output {
        self.arena[id].get()
    }
}

impl<'a> IntoIterator for &'a DocumentTree {
    type Item = NodeId;
    type IntoIter = indextree::Descendants<'a, DocumentNode>;

    fn into_iter(self) -> Self::IntoIter {
        self.root.descendants(&self.arena)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_slugify() {
        assert_eq!(DocumentNode::slugify("Hello World"), "hello-world");
        assert_eq!(DocumentNode::slugify("Section 1.2.3"), "section-1-2-3");
        assert_eq!(DocumentNode::slugify("  Trim  Me  "), "trim-me");
        assert_eq!(DocumentNode::slugify("UPPERCASE"), "uppercase");
        assert_eq!(DocumentNode::slugify("TÍTULO PRELIMINAR"), "título-preliminar");
        assert_eq!(DocumentNode::slugify_ascii("TÍTULO PRELIMINAR"), "titulo-preliminar");
    }

    #[test]
    fn test_section_creation() {
        let sec = DocumentNode::section(2, "Getting Started");
        assert!(sec.is_section());
        assert_eq!(sec.section_level(), Some(2));
        assert_eq!(sec.anchor, Some("getting-started".to_string()));
        assert_eq!(sec.content, "Getting Started");
    }

    #[test]
    fn test_tree_construction() {
        let mut tree = DocumentTree::new();
        let root = tree.root();

        let sec1 = tree.add_child(root, DocumentNode::section(1, "Introduction"));
        let sec2 = tree.add_child(root, DocumentNode::section(1, "Methods"));
        let subsec = tree.add_child(sec2, DocumentNode::section(2, "Participants"));

        assert_eq!(tree.hierarchical_path(sec1), "1");
        assert_eq!(tree.hierarchical_path(sec2), "2");
        assert_eq!(tree.hierarchical_path(subsec), "2.1");
    }

    #[test]
    fn test_anchor_lookup() {
        let mut tree = DocumentTree::new();
        tree.add_child(tree.root(), DocumentNode::section(1, "Introduction"));
        tree.add_child(tree.root(), DocumentNode::section(1, "Results"));
        tree.add_child(tree.root(), DocumentNode::section(1, "TÍTULO PRELIMINAR"));

        assert!(tree.find_by_anchor("introduction").is_some());
        assert!(tree.find_by_anchor("results").is_some());
        assert!(tree.find_by_anchor("título-preliminar").is_some());
        assert!(tree.find_by_anchor("titulo-preliminar").is_some());
        assert!(tree.find_by_anchor("nonexistent").is_none());
    }

    #[test]
    fn test_path_navigation() {
        let mut tree = DocumentTree::new();
        let sec1 = tree.add_child(tree.root(), DocumentNode::section(1, "A"));
        let sec2 = tree.add_child(sec1, DocumentNode::section(2, "B"));

        assert_eq!(tree.find_by_path("1").unwrap(), sec1);
        assert_eq!(tree.find_by_path("1.1").unwrap(), sec2);
        assert!(tree.find_by_path("1.2").is_err());
        assert!(tree.find_by_path("invalid").is_err());
    }

    #[test]
    fn test_parent_section() {
        let mut tree = DocumentTree::new();
        let section = tree.add_child(tree.root(), DocumentNode::section(1, "Parent"));
        let paragraph = tree.add_child(section, DocumentNode::new(NodeKind::Paragraph, "text"));

        assert_eq!(tree.parent_section(paragraph).unwrap(), section);
        assert!(tree.parent_section(section).is_none()); // Parent is root, not a section
    }

    #[test]
    fn test_sections_list() {
        let mut tree = DocumentTree::new();
        tree.add_child(tree.root(), DocumentNode::section(1, "First"));
        let sec = tree.add_child(tree.root(), DocumentNode::section(1, "Second"));
        tree.add_child(sec, DocumentNode::section(2, "Nested"));

        let sections = tree.sections();
        assert_eq!(sections.len(), 3);

        // Check ordering (pre-order)
        assert_eq!(sections[0].anchor, "first");
        assert_eq!(sections[1].anchor, "second");
        assert_eq!(sections[2].anchor, "nested");
    }
}
