[package]
name              = "canary-server"
publish.workspace = true

authors.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true
version.workspace    = true

[dependencies]
anstream = "1.0.0"
anstyle = "1.0.14"
async-trait.workspace = true
aws-config.workspace = true
aws-credential-types.workspace = true
aws-sdk-s3.workspace = true
aws-types.workspace = true
axum.workspace = true
base64 = "0.22.1"
bytes.workspace = true
chrono.workspace = true
config.workspace = true
database = { workspace = true, default-features = false }
document-hierarchy = { path = "../parser" }
futures-util = "0.3.31"
headers.workspace = true
http.workspace = true
human-panic.workspace = true
humantime-serde.workspace = true
infer.workspace = true
miette = { workspace = true, features = ["fancy-no-backtrace"] }
mime.workspace = true
mime_guess.workspace = true
object_store = { workspace = true, features = ["aws", "fs"] }
public-id = { path = "../public-id" }
rmcp = { version = "1.7.0", default-features = false, features = [
  "server",
  "macros",
  "transport-streamable-http-server",
] }
schemars = "1.2.1"
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
shadow-rs = { version = "2.0.0", default-features = false }
smol_str.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true
tower = { workspace = true, features = ["timeout", "util"] }
tower-http = { workspace = true, features = [
  "catch-panic",
  "compression-full",
  "fs",
  "limit",
  "normalize-path",
  "request-id",
  "sensitive-headers",
  "timeout",
  "trace",
] }
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
zeroize.workspace = true

[features]
default = ["surreal-embedded-mem", "surreal-remote-ws"]
surreal-all = [
  "surreal-embedded-mem",
  "surreal-embedded-rocksdb",
  "surreal-embedded-surrealkv",
  "surreal-remote-http",
  "surreal-remote-ws",
]
surreal-embedded-mem = ["database/embedded-mem"]
surreal-embedded-rocksdb = ["database/embedded-rocksdb"]
surreal-embedded-surrealkv = ["database/embedded-surrealkv"]
surreal-remote-http = ["database/remote-http"]
surreal-remote-ws = ["database/remote-ws"]

[dev-dependencies]
crc64fast-nvme     = "1.2.1"
reqwest            = { version = "0.12.24", default-features = false, features = ["json", "rustls-tls"] }
tempfile.workspace = true

[build-dependencies]
rusty-figlet = { version = "0.3.5", default-features = false }
shadow-rs    = { version = "2.0.0", default-features = false, features = ["build"] }
