[package]
name              = "canary-server"
publish.workspace = true

authors.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true
version.workspace    = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
axum-extra = { version = "0.12.6", features = ["attachment"] }
axum_typed_multipart = { version = "0.16.5", features = ["tempfile_3"] }
bytes.workspace = true
chrono.workspace = true
config.workspace = true
document-hierarchy = { path = "../parser" }
futures-util = "0.3.31"
headers.workspace = true
http.workspace = true
human-panic.workspace = true
humantime-serde.workspace = true
infer.workspace = true
mime.workspace = true
mime_guess.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
smol_str.workspace = true
surrealdb.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true
tower = { workspace = true, features = ["timeout", "util"] }
tower-http = { workspace = true, features = [
  "catch-panic",
  "compression-full",
  "fs",
  "limit",
  "normalize-path",
  "request-id",
  "sensitive-headers",
  "timeout",
  "trace",
] }
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true

[features]
default = ["surreal-embedded-mem", "surreal-remote-ws"]
surreal-all = [
  "surreal-embedded-mem",
  "surreal-embedded-rocksdb",
  "surreal-embedded-surrealkv",
  "surreal-remote-http",
  "surreal-remote-ws",
]
surreal-embedded-mem = ["surrealdb/kv-mem"]
surreal-embedded-rocksdb = ["surrealdb/kv-rocksdb"]
surreal-embedded-surrealkv = ["surrealdb/kv-surrealkv"]
surreal-remote-http = ["surrealdb/protocol-http"]
surreal-remote-ws = ["surrealdb/protocol-ws"]

[dev-dependencies]
tempfile.workspace = true
